# Generated by Django 4.0.4 on 2022-05-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40,)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=40)),
                ('unidad', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(max_length=40)),
                ('familia', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('rubro', models.CharField(max_length=40)),
                ('tarea', models.CharField(max_length=40)),
                ('unidad', models.CharField(max_length=40)),
                ('costo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('especificacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Homeworks',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
