# Generated by Django 3.2.4 on 2022-06-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_course', '0004_auto_20220621_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user_profile',
            new_name='profile_image',
        ),
    ]
